server:
  port: ${port:8881}
xxl:
  job:
    admin:
      addresses: http://192.168.1.150:8888/xxl-job-admin
    executor:
#      appname: xxl-job-executor-sample
      appname: xxl-job-sharding-executor
      port: ${executor.port:9999}
    accessToken: default_token